ivory_ck_editor:
    input_sync: true
    configs:
        my_config:
            toolbar: [ ['Bold','Italic','Underline'],[ 'NumberedList','BulletedList' ], ['About' ]]
        my_config_inicio:
            toolbar: [ ['Source','Format'],['Bold','Italic','Underline'],[ 'NumberedList','BulletedList' ], ['About' ]]