web:
    resource: "@WebBundle/Controller/"
    type:     annotation
    prefix:   /

secure:
    resource: "@SecureBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
api_login_check:
    path: /api/login_check
