security:
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    
    providers:
        user_db:
            entity: { class: AppBundle\Entity\Usuario, property: username }
        web_db:
            entity: { class: AppBundle\Entity\Usuario, property: correo }
        chain_provider:
                chain:
                    providers: [user_db, web_db]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/user/seguridad/inicioSesion$
            security: false
        
        # Firewall modulo administracion
        secured_area:
            pattern:    ^/administracion/*
            provider: user_db
            form_login:
                check_path: web_login_check
                login_path: inicio
                default_target_path: /user
                always_use_default_target_path: true
            logout:
                path:   web_logout
                target: /
                
        # Firewall modulo consulta web
        secured_web:
            pattern:    ^/web/*
            provider: web_db
            form_login:
                check_path: web_login_check
                login_path: inicio
                default_target_path: /user
                always_use_default_target_path: true
            logout:
                path:   web_logout
                target: /
        # Firewall modulo consulta web
        login_web:
            pattern:    ^/user
            provider: chain_provider
            form_login:
                check_path: web_login_check
                login_path: inicio
                default_target_path: /user
                always_use_default_target_path: true
            logout:
                path:   web_logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/user/seguridad/inicioSesion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/web/*, roles: ROLE_USER }
        - { path: ^/administracion/*, roles: ROLE_ADMIN }
        - { path: ^/user, roles: [ROLE_USER, ROLE_ADMIN]}
        
