security:
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    
    providers:
        user_db:
            entity: { class: AppBundle\Entity\Usuario, property: username }
        web_db:
            entity: { class: AppBundle\Entity\Usuario, property: correo }
        chain_provider:
                chain:
                    providers: [user_db, web_db]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/user/seguridad/inicioSesion$
            security: false

        registroWeb:
            pattern:  ^/web/registro$
            security: false

        registrarWeb:
            pattern:  ^/web/registrar$
            security: false
        registro:
            pattern: ^/movil/registrar
            security: false

        validacion:
            pattern: ^/movil/validar
            security: false

        registroRedes:
            pattern: ^/movil/registroRedesMovil
            security: false

        recuperarContrasena:
            pattern: ^/movil/recuperarContrasena
            security: false    

        movil:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern:   ^/movil
            stateless: true
            lexik_jwt: ~
        
        # Firewall modulo administracion
        secured_area:
            pattern:    ^/administracion/*
            context: website
            provider: user_db
            form_login:
                check_path: web_login_check
                login_path: inicio
                default_target_path: /user
                always_use_default_target_path: true
            logout:
                path:   web_logout
                target: /user
                
        # Firewall modulo consulta web
        #secured_web:
         #   pattern:    ^/web/*
          #  context: website
           # provider: web_db
            #form_login:
             #   check_path: web_login_check
              #  login_path: inicio
               # default_target_path: /user
                #always_use_default_target_path: true
            #logout:
             #   path:   web_logout
              #  target: /user
        # Firewall modulo consulta web
        secured_home:
            pattern:    ^/*
            provider: web_db
            anonymous: ~
            form_login:
                check_path: web_login_check
                login_path: inicio
                default_target_path: /
            logout:
                path:   web_logout
                target: /
        # Firewall modulo consulta web
        login_web:
            pattern:    ^/user
            context: website
            provider: chain_provider
            form_login:
                check_path: web_login_check
                login_path: inicio
                default_target_path: /user
                always_use_default_target_path: true
            logout:
                path:   web_logout
                target: /user
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"


    access_control:
        - { path: ^/user/seguridad/inicioSesion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registrar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/web/*, roles: ROLE_USER }
        - { path: ^/administracion/*, roles: ROLE_ADMIN }
        - { path: ^/user, roles: [ROLE_USER , ROLE_ADMIN]}
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/*, roles: [ROLE_USER, IS_AUTHENTICATED_ANONYMOUSLY] }
        
