# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    paginador:
        class: Servicios\Paginacion
    correo:
        class: Servicios\Email
        arguments: ['@mailer', '@templating', '@service_container']
    notificaciones:
        class: Servicios\Notificaciones