<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloRepository extends EntityRepository
{
	public function getArticulosEstablecimiento($id){
		$em = $this->getEntityManager();
		$consulta = $em->createQueryBuilder()
                        ->addSelect('a')
                        ->from('AppBundle:Articulo', 'a')
                        ->where('a.establecimiento = :establecimiento')->setParameter('establecimiento',$id)
                        ->andWhere('a.cantidad > 0');
        return $consulta->getQuery()->getResult();
	}

    public function autocompletar($palabra){
        $em = $this->getEntityManager();

        $consulta = $em->createQueryBuilder()
            ->addSelect('a.nombre')
            ->from('AppBundle:Articulo', 'a')
            ->where('lower(a.nombre) like :palabra')->setParameter('palabra','%'.$palabra.'%')
            ->andWhere('a.cantidad > 0');

        return $consulta->getQuery()->getResult();
    }

    public function realizarBusqueda($palabra){
        $em = $this->getEntityManager();

        $consulta = $em->createQueryBuilder()
            ->Select('a')
            ->from('AppBundle:Articulo', 'a')
            ->where('a.nombre like :palabra')->setParameter('palabra','%'.$palabra.'%')
            ->andWhere('a.cantidad > 0');

        return $consulta->getQuery()->getResult();
    }

    public function obtenerArticulosEstablecimiento($idEstablecimiento){
        $em = $this->getEntityManager();
        $consulta = $em->createQueryBuilder()
            ->select('a')
            ->from('AppBundle:Articulo','a')
            ->where('a.establecimiento = :idEstablecimiento')
            ->andWhere('a.cantidad > 0')
            ->setParameter('idEstablecimiento',$idEstablecimiento);
        return $consulta->getQuery()->getResult();
    }

    public function obtenerArticulosDestacados($idCategoria = null){
        $em = $this->getEntityManager();

        $consulta = $em->createQueryBuilder()
            ->select('a')
            ->from('AppBundle:Articulo','a')
            ->andWhere('a.cantidad > 0')
            ->setMaxResults(4);

        return $consulta->getQuery()->getResult();
    }
}
