<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloRepository extends EntityRepository
{
	public function getArticulosEstablecimiento($id){
		$em = $this->getEntityManager();

		$consulta = $em->createQueryBuilder()
                        ->addSelect('a')
                        ->from('AppBundle:Articulo', 'a')
                        ->where('a.establecimiento = :establecimiento')->setParameter('establecimiento',$id)
                        ->andWhere('a.cantidad > 0');
        

        return $consulta->getQuery()->getResult();
	}
}
