<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarritoRepository extends EntityRepository
{
    public function buscarCarritosVencidos(){
        $em = $this->getEntityManager();
        $consulta = $em->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:Carrito','c')
            ->where('c.usuario IS NULL')
            ->andWhere('c.fechaLimite = :fecha')
            ->setParameter('fecha',new \DateTime());
        return $consulta->getQuery()->getResult();
    }
}
