<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{
	public function findTodos(){
		$em = $this->getEntityManager();

		$consulta = $em->createQueryBuilder()
                        ->addSelect('c')
                        ->from('AppBundle:Categoria', 'c');
        return $consulta->getQuery();
	}
}
