<?php

namespace AppBundle\Entity;

/**
 * CuponUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuponUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
