<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CuponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuponRepository extends EntityRepository
{
    public function buscarCupon($codigo){
        $em = $this->getEntityManager();
        $fecha = new \DateTime();
        $consulta = $em->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:Cupon','c')
            ->where('c.codigo = :codigo')
            ->andWhere('c.estado = :estado')
            ->andWhere('c.fechaLimite >= :fecha')
            ->setParameter('codigo',$codigo)
            ->setParameter('estado','Activo')
            ->setParameter('fecha',$fecha);

        return $consulta->getQuery()->getOneOrNullResult();
    }

    public function validarCupon($cupon,$usuario){
        $em = $this->getEntityManager();

        $consulta = $em->createQueryBuilder()
            ->select('cu')
            ->from('AppBundle:CuponUsuario','cu')
            ->innerJoin('cu.cupon','c')
            ->innerJoin('c.pedidos','p')
            ->innerJoin('p.usuario','u')
            ->where('c.id = :cupon')
            ->andWhere('cu.usuario = :usuario')
            ->andWhere('u.id = :usuario')
            ->setParameter('cupon',$cupon)
            ->setParameter('usuario',$usuario)
            ;
        return $consulta->getQuery()->getOneOrNullResult();
    }


}
