<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstablecimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstablecimientoRepository extends EntityRepository
{
    public function findTodos(){
        $em = $this->getEntityManager();

        $consulta = $em->createQueryBuilder()
            ->addSelect('e')
            ->from('AppBundle:Establecimiento', 'e');


        $consulta->orderBy('e.peso', 'ASC');

        return $consulta;
    }

    public function findTodosCategoria($idCategoria){
        $em = $this->getEntityManager();

        $consulta = $em->createQueryBuilder()
            ->addSelect('e')
            ->from('AppBundle:Establecimiento', 'e')
            ->where('e.categoria = :categoria')->setParameter('categoria',$idCategoria);


        $consulta->orderBy('e.peso', 'ASC');

        return $consulta;
    }


	public function findEstablecimientosCategoria($id){
		$em = $this->getEntityManager();

		$consulta = $em->createQueryBuilder()
                        ->addSelect('e')
                        ->from('AppBundle:Establecimiento', 'e')
                        ->where('e.categoria = :categoria')->setParameter('categoria',$id);
                $consulta->setMaxResults(3);
                $consulta->orderBy('e.peso', 'ASC');

                return $consulta->getQuery()->getResult();
	}

	public function obtenerEstablecimintosDestacados($idCategoria = null){
        $em = $this->getEntityManager();

        $consulta = $em->createQueryBuilder()
                       ->select('e')
                       ->from('AppBundle:Establecimiento','e')
                       ->setMaxResults(4);
        if($idCategoria){
            $consulta->innerJoin('e.categoria','c')
                     ->andWhere('c.id = :id')
                     ->setParameter('id',$idCategoria);
        }

        return $consulta->getQuery()->getResult();
    }
    public function obtenerTodosEstablecimintosDestacados(){
        $em = $this->getEntityManager();

        $consulta = $em->createQueryBuilder()
            ->select('e')
            ->from('AppBundle:Establecimiento','e')
            ->setMaxResults(12);


        return $consulta->getQuery()->getResult();
    }
}
