<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstablecimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstablecimientoRepository extends EntityRepository
{
	public function findEstablecimientosCategoria($id){
		$em = $this->getEntityManager();

		$consulta = $em->createQueryBuilder()
                        ->addSelect('e')
                        ->from('AppBundle:Establecimiento', 'e')
                        ->where('e.categoria = :categoria')->setParameter('categoria',$id);
                $consulta->setMaxResults(4);
                $consulta->orderBy('e.peso', 'ASC');

                return $consulta->getQuery()->getResult();
	}
}
