<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoRepository extends EntityRepository
{
    public function listarPedidos($usuario){
        $em = $this->getEntityManager();
        $consulta = $em->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:Pedido','p')
            ->where('p.usuario = :usuario')
            ->andWhere('p.estado <> :estado')
            ->setParameter('usuario',$usuario)
            ->setParameter('estado','En Progreso');
        return $consulta->getQuery()->getResult();
    }

    public function listarPedidosActivos($usuario){
        $em = $this->getEntityManager();
        $consulta = $em->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:Pedido','p')
            ->where('p.usuario = :usuario')
            ->andWhere('p.estado = :estado')
            ->setParameter('usuario',$usuario)
            ->setParameter('estado','En Progreso');
        return $consulta->getQuery()->getResult();
    }

    public function buscarReservas(){
        $em = $this->getEntityManager();
        $consulta = $em->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:Pedido','p')
        ->orderBy('p.fechaCreacion',"DESC");

        return $consulta->getQuery()->getResult();
    }

    public function buscarReservasEstados($filtro){
        $em = $this->getEntityManager();
        $consulta = $em->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:Pedido','p')
            ->andWhere('p.estado = :estado')
            ->setParameter('estado',$filtro)
            ->orderBy('p.fechaCreacion',"DESC");
        return $consulta->getQuery()->getResult();
    }
}
