<?php

namespace AppBundle\Entity;

/**
 * PromocionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromocionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPromocionesActivas(){
        $em = $this->getEntityManager();
        $fecha = new \DateTime();
        $fecha->setTime("00","00","00");
        $consulta = $em->createQueryBuilder()
            ->addSelect('p')
            ->from('AppBundle:Promocion', 'p')
            ->where(':fecha BETWEEN p.fechaInicio AND p.fechaFin')
            ->setParameter('fecha',$fecha);
        return $consulta->getQuery()->getResult();
    }

}
