<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
	public function findTodos(){
		$em = $this->getEntityManager();
        $consulta = $em->createQueryBuilder()
                        ->select('u')
                        ->from('AppBundle:Usuario', 'u');
        return $consulta->getQuery();
	}

    public function findUsuarioAdministrativos(){
        $em = $this->getEntityManager();
        $consulta = $em->createQueryBuilder()
            ->select('u')
            ->from('AppBundle:Usuario', 'u')
            ->innerJoin('u.rol','r')
            ->where('r.codigo = :codigo')
            ->setParameter('codigo','ROLE_ADMIN')
        ;

        return $consulta->getQuery()->getResult();
    }

}
